version: '3.8'

services:

    server:
      build: backend
      image: wingsuited123/inno_backend
      ports:
        - '3031:3031'

    client:
      build: frontend
      image: wingsuited123/inno_frontend
      ports:
        - '80:4200'